//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuCPULib.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ascii {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ascii() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimuCPULib.Resources.Ascii", typeof(Ascii).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AsciiSettings xmlns=&quot;http://www.bajdcc.com&quot;&gt;
        ///  &lt;Fonts&gt;
        ///    &lt;Font Code=&quot;48&quot;&gt;
        ///      &lt;Path&gt;
        ///        &lt;Line&gt;
        ///          &lt;Points&gt;
        ///            &lt;From X=&quot;2&quot; Y=&quot;3&quot;&gt;&lt;/From&gt;
        ///            &lt;To X=&quot;4&quot; Y=&quot;1&quot;&gt;&lt;/To&gt;
        ///            &lt;To X=&quot;12&quot; Y=&quot;1&quot;&gt;&lt;/To&gt;
        ///            &lt;To X=&quot;14&quot; Y=&quot;3&quot;&gt;&lt;/To&gt;
        ///          &lt;/Points&gt;
        ///        &lt;/Line&gt;
        ///        &lt;Copy Vertical=&quot;false&quot; Flip=&quot;true&quot; Src=&quot;1&quot; Dst=&quot;4&quot; Count=&quot;3&quot;&gt;&lt;/Copy&gt;
        ///      &lt;/Path&gt;
        ///    &lt;/Font&gt;
        ///    &lt;Font Code=&quot;49&quot;&gt;
        ///      &lt;Path&gt;
        ///        &lt;Line&gt;
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AsciiXml {
            get {
                return ResourceManager.GetString("AsciiXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nop
        ///mov ah,02h
        ///mov dl,&apos;0&apos;
        ///.LOOP
        ///int 21h
        ///inc dl
        ///#jmp loop
        ///halt 的本地化字符串。
        /// </summary>
        internal static string TestInst {
            get {
                return ResourceManager.GetString("TestInst", resourceCulture);
            }
        }
    }
}
